# Generated by Django 2.0.7 on 2018-10-01 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_price', models.PositiveIntegerField(help_text='Price of product in cents')),
                ('sale_date_start', models.DateField(help_text='Start of sale pricing')),
                ('sale_date_end', models.DateField(blank=True, help_text='End of sale pricing', null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
        ),
    ]
